

export const CreationDefaults = {
  X_TILES_DEFAULT: 30,
  Y_TILES_DEFAULT: 20,

  OUTER_TILE_COLOR: "#939799",
  OUTER_TILE_LINE_THICKNESS: 1,
  INNER_TILE_COLOR: "cyan",
  INNER_TILE_LINE_THICKNESS: 1,
  OUTER_SELECTED_COLOR: "orange",

  OBJECT_COLOR_DEFAULT: "#000000",
}