export const Landscapes = [
  {
    name: 'Test 1',
    json: '{"name":"Test 1","bgColor":"#b1f7f0","xTiles":30,"yTiles":20,"objects":[{"name":"w2","type":"WALL","color":"#571aff","iXStart":4,"iYStart":3,"iXEnd":18,"iYEnd":3},{"name":"w3","type":"WALL","color":"#571aff","iXStart":25,"iYStart":3,"iXEnd":26,"iYEnd":7},{"name":"w4","type":"WALL","color":"#1aff71","iXStart":9,"iYStart":10,"iXEnd":17,"iYEnd":14}]}'
  },
  {
    name: 'Test 2',
    json: '{"name":"Test 2","bgColor":"#c0afee","xTiles":25,"yTiles":27,"objects":[{"name":"w5","type":"WALL","color":"#1aff71","iXStart":6,"iYStart":9,"iXEnd":9,"iYEnd":11},{"name":"w6","type":"WALL","color":"#1aff71","iXStart":20,"iYStart":1,"iXEnd":20,"iYEnd":5},{"name":"w7","type":"WALL","color":"#1aff71","iXStart":16,"iYStart":14,"iXEnd":18,"iYEnd":19},{"name":"w8","type":"WALL","color":"#1a40ff","iXStart":6,"iYStart":16,"iXEnd":9,"iYEnd":17},{"name":"w9","type":"WALL","color":"#1a40ff","iXStart":4,"iYStart":23,"iXEnd":9,"iYEnd":24},{"name":"w10","type":"WALL","color":"#a31aff","iXStart":3,"iYStart":3,"iXEnd":3,"iYEnd":3},{"name":"w11","type":"WALL","color":"#a31aff","iXStart":6,"iYStart":1,"iXEnd":9,"iYEnd":3},{"name":"w12","type":"WALL","color":"#a31aff","iXStart":14,"iYStart":3,"iXEnd":16,"iYEnd":9},{"name":"w13","type":"WALL","color":"#a31aff","iXStart":20,"iYStart":22,"iXEnd":21,"iYEnd":23},{"name":"w14","type":"WALL","color":"#a31aff","iXStart":21,"iYStart":11,"iXEnd":22,"iYEnd":11},{"name":"w15","type":"WALL","color":"#a31aff","iXStart":2,"iYStart":10,"iXEnd":2,"iYEnd":13}]}'
  },
  {
    name: 'Blue Floral',
    json: '{"name":"Blue Floral","bgColor":"#535ef9","xTiles":20,"yTiles":20,"objects":[{"name":"w1","type":"WALL","color":"#7cff6b","iXStart":5,"iYStart":1,"iXEnd":5,"iYEnd":3},{"name":"w2","type":"WALL","color":"#7cff6b","iXStart":1,"iYStart":5,"iXEnd":3,"iYEnd":5},{"name":"w3","type":"WALL","color":"#7cff6b","iXStart":14,"iYStart":1,"iXEnd":14,"iYEnd":3},{"name":"w4","type":"WALL","color":"#7cff6b","iXStart":16,"iYStart":5,"iXEnd":18,"iYEnd":5},{"name":"w5","type":"WALL","color":"#7cff6b","iXStart":16,"iYStart":14,"iXEnd":18,"iYEnd":14},{"name":"w6","type":"WALL","color":"#7cff6b","iXStart":14,"iYStart":16,"iXEnd":14,"iYEnd":18},{"name":"w7","type":"WALL","color":"#7cff6b","iXStart":5,"iYStart":16,"iXEnd":5,"iYEnd":18},{"name":"w8","type":"WALL","color":"#7cff6b","iXStart":1,"iYStart":14,"iXEnd":3,"iYEnd":14},{"name":"w9","type":"WALL","color":"#6beeff","iXStart":1,"iYStart":1,"iXEnd":1,"iYEnd":1},{"name":"w10","type":"WALL","color":"#6beeff","iXStart":18,"iYStart":1,"iXEnd":18,"iYEnd":1},{"name":"w11","type":"WALL","color":"#6beeff","iXStart":1,"iYStart":18,"iXEnd":1,"iYEnd":18},{"name":"w12","type":"WALL","color":"#6beeff","iXStart":18,"iYStart":18,"iXEnd":18,"iYEnd":18},{"name":"w13","type":"WALL","color":"#c7a8ff","iXStart":9,"iYStart":3,"iXEnd":10,"iYEnd":7},{"name":"w14","type":"WALL","color":"#c7a8ff","iXStart":9,"iYStart":12,"iXEnd":10,"iYEnd":16},{"name":"w15","type":"WALL","color":"#a575ff","iXStart":5,"iYStart":9,"iXEnd":6,"iYEnd":10},{"name":"w16","type":"WALL","color":"#a575ff","iXStart":13,"iYStart":9,"iXEnd":14,"iYEnd":10}]}'
  },
];